version: '2.1'

services:
  web:
    build: .
    image: joshuamarquez/dyn-nginx:latest
    container_name: dyn-nginx
    ports:
     - 8081:80
    environment:
      TEMPLATES: NODE_JS_SOCKET_IO,MONGODB
      NODE_JS_SOCKET_IO_PORT: 80
      NODE_JS_SOCKET_IO_TARGET: app:8080